[workspace]
members = ["backend"]
resolver = "2"

[workspace.package]
edition = "2024"
homepage = "https://github.com/lakekeeper/lakekeeper"
repository = "https://github.com/lakekeeper/lakekeeper.git"
rust-version = "1.86.0"
license = "Apache-2.0"
