name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:

    runs-on: ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v4.2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: rust
